name: pokedex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.7
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/pokedexicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokeball.png
